# Colors:
#   BLACK = &0, DARK_BLUE = &1, DARK_GREEN = &2, DARK_AQUA = &3
#   DARK_RED = &4, DARK_PURPLE = &5, GOLD = &6, GRAY = &7
#   DARK_GRAY = &8, BLUE = &9, GREEN = &a, AQUA = &b
#   RED = &c, LIGHT_PURPLE = &d, YELLOW = &e, WHITE = &f

# Formats:
#   OBFUSCATED = &k, BOLD = &l, STRIKETHROUGH = &m,
#   UNDERLINE = &n, ITALIC = &o, RESET = &r

messages:
  # messages for help
  help:
    - "&e--------- &rHelp: Mention &e--------------------------------&r"
    - "&7Below is a list of all Mention commands:&r"
    - "&6/mention reload: &rReload this plugin"

  # message for title
  title: "&e&lYou're mentioned by %s"

  # message for subtitle
  subtitle: "&e&lYou're mentioned by %s"

  # message for actionbar
  actionbar: "&e&lYou're mentioned by %s"

  # message when plugin reloading
  reloading: "&cReloading plugin..."

  # message when plugin reloaded
  reloaded: "&aPlugin reloaded!"

settings:
  # 0 for title, 1 for subtitle, 2 for actionbar
  mode: 1

  # 1 unit = 1 tick
  run-after: 20

  # 1 unit = 1 tick (Only affect title and subtitle)
  title-fade-in: 2

  # 1 unit = 1 tick (Only affect title and subtitle)
  title-stay: 40

  # 1 unit = 1 tick (Only affect title and subtitle)
  title-fade-out: 2

